### PR TITLE
Update the minimal vscode engine version to 1.30.0

### PR DESCRIPTION
**Pull request by CvX**
Fixes the build – the code depends on `Declaration` and `LocationLink` types introduced in 1.30.0.

### CODE REVIEW

**Comment by CvX** [comment]
(I'll rebase other PRs after this one gets merged so their tests can pass)

**Comment by CvX** [comment]
ping @SamVerschueren

**Comment by CvX** [comment]
Ping @SamVerschueren? 🙂 (I’m probably going to publish a fork next week)

**Comment by SamVerschueren** [comment]
I'll try to take a look. Sorry for the late reply.

**Comment by SamVerschueren** [comment]
Thanks!

**Comment by SamVerschueren** [comment]
@CvX Thanks for all the PRs. Feel free to cut a new release :).

**Pull request merged**
