### PR TITLE
feat: massive refactor and fix for xo 40 +

### PR DESCRIPTION
**Pull request by Spence-S**
I forked and published this package as a new extension - since it seems this is no longer being maintained or accepting PRs. This PR is a giant deviation so I don't necessarily expect it to get approved, although I would love to get the issue hunt reward for #91 💯  - but no big deal either way!

Please try this via the link below, and feel free to file issues in my fork. My extension should work now for all versions of XO. 

If for some reason this PR does get some attention - I would be happy to become the maintainer of this repo and archive my fork - and find some way to merge the extensions to promote oneness in the community or whatever!

My published extension can be found below:
https://marketplace.visualstudio.com/items?itemName=spence-s.linter-xo

### CODE REVIEW

**Comment by Spence-S** [comment]
also the reason I removed TS from the project was 

1) I don't really use TS so I found it distracting. 
2) I solved this by using dynamic imports for importing the xo which are not yet supported. https://github.com/microsoft/TypeScript/issues/45125

**Comment by lolPants** [comment]
> Please try this via the link below, and feel free to file issues in my fork.

Your fork has issues disabled.

**Comment by Spence-S** [comment]
> > Please try this via the link below, and feel free to file issues in my fork.
> 
> Your fork has issues disabled.

Fixed now, thanks!

**Comment by SamVerschueren** [comment]
@Spence-S would you be open to be added to this repo and take the maintenance/development/release on you? I don't have the time to do any active work on this anymore.

**Comment by Spence-S** [comment]
@SamVerschueren yes - that would be ideal. Not sure how extension ownership/permissions work but I'd be happy to maintain as much as needed and keep the community unified on a single solution.

**Comment by SamVerschueren** [comment]
Awesome! I'll make sure to do the necessary steps!

**Comment by yakov116** [comment]
@Spence-S can you please request the bounty so I can credit you?

**Comment by Spence-S** [comment]
@yakov116 Thank you so much for this! I submitted this PR against the issue some time ago. I don't see a way I can do anything else. My submitted PR links directly to this page. 🤷🏻‍♂️

**Review by yakov116 — COMMENTED** [review]
Lets see if this works

**Comment by yakov116** [comment]
@can you close the issue? Maybe that will allow me to award you?

**Comment by Spence-S** [comment]
@yakov116 done

**Comment by SamVerschueren** [comment]
@Spence-S Do you have Twitter so we can chat through DM regarding publish rights for this extension? Or should I just drop you an email?

**Comment by Spence-S** [comment]
@SamVerschueren sent you a dm on Twitter

**Pull request merged**
