### PR TITLE
Add package-lock.json for the client and the server

### PR DESCRIPTION
**Pull request by CvX**
Currently `yarn install` in a freshly cloned repo leaves the working tree dirty.
Those lockfiles should either be added to gitignore or, preferably, be committed to the repo (as this PR does).

### CODE REVIEW

**Comment by SamVerschueren** [comment]
@CvX you talk about `yarn install` but add the `package-lock.json` files in here? Instead I would add a `.npmrc` file in with the contents `package-lock=false`.

**Comment by SamVerschueren** [comment]
You probably meant `npm install` as the yarn lock files are published. So add the `.npmrc` file instead so we only work with one lock file system, being yarn.

**Comment by CvX** [comment]
Oh, I do mean `yarn`! 🙂

The `postinstall` script defined in `package.json` runs `npm install` in client and server directories, which creates `package-lock.json` files.

In what situations are `client/yarn.lock` and `server/yarn.lock` created/updated? Other than manually?

**Comment by osdiab** [comment]
Seems like the real move is for the postinstall script to not use `npm`.

**Comment by Spence-S** [comment]
No longer relevant with the new structure.

**Pull request closed without merging**
