### PR TITLE
Performance Improvement

### LINKED ISSUE #22: Very slow
I don't know if this is the linter, xo or some plugin, but XO results are extremely slow. It is as if every keystroke results in a lint, instead of only linting if the previous run completed and the text is dirty again.

On "larger" files (400 lines) this becomes very noticeable, taking tens of seconds/minutes.

Anything I can do to troubleshoot?

### PR DESCRIPTION
**Pull request by xlc**
Fixes #22 and #29 

I basically just copy implementation from vscode-eslint.

BufferedMessageQueue copied from https://github.com/Microsoft/vscode-eslint/blob/ad394e3eabfa89c78c38904d71d9aebf64b7edfa/server/src/server.ts

This is first time I am working with vscode extension and I haven't done much testing with it. Let me know if you find any issues.

I really would like to have this issue solved because the current extension is unusable slow to me.

### CODE REVIEW

**Comment by SamVerschueren** [comment]
I will look at it when I find some time. Thanks for working on this!

**Comment by xlc** [comment]
@SamVerschueren Any updates?

**Comment by xlc** [comment]
@SamVerschueren Do you want to merge this? and make a release with it?

**Comment by SamVerschueren** [comment]
Thanks @xlc!!!! :tada: Will have a look at releasing this one.

**Pull request merged**
